export const languages = [
  { value: "English", label: "English" },
  { value: "Français", label: "French" },
  { value: "Bamanankan", label: "Bamanankan" },
  { value: "日本語", label: "Japanese" },
  { value: "Français", label: "French" },
  { value: "Bamanankan", label: "Bamanankan" },
  { value: "Bokmål", label: "Norwegian Bokmål" },
  { value: "Latviešu", label: "Latvian" },
  { value: "Tiếng Việt", label: "Vietnamese" },
  { value: "广州话 / 廣州話", label: "Cantonese" },
  { value: "עִבְרִית", label: "Hebrew" },
  { value: "Český", label: "Czech" },
  { value: "Український", label: "Ukrainian" },
  { value: "Polski", label: "Polish" },
  { value: "Srpski", label: "Serbian" },
  { value: "shqip", label: "Albanian" },
  { value: "Hrvatski", label: "Croatian" },
  { value: "Português", label: "Portuguese" },
  { value: "Cymraeg", label: "Welsh" },
  { value: "ελληνικά", label: "Greek" },
  { value: "Malti", label: "Maltese" },
  { value: "Gaeilge", label: "Irish" },
  { value: "Esperanto", label: "Esperanto" },
  { value: "Latin", label: "Latin" },
  { value: "Wolof", label: "Wolof" },
  { value: "پښتو", label: "Pashto" },
  { value: "বাংলা", label: "Bengali" },
  { value: "한국어/조선말", label: "Korean" },
  { value: "svenska", label: "Swedish" },
];

export const directors = [
  { value: "Joe Dante", label: "Joe Dante" },
  { value: "Doug McHenry", label: "Doug McHenry" },
  { value: "Rob Epstein", label: "Rob Epstein" },
  { value: "Jean-Paul Rappeneau", label: "Jean-Paul Rappeneau" },
  { value: "Jodie Foster", label: "Jodie Foster" },
  { value: "Desmond Nakano", label: "Desmond Nakano" },
  { value: "Sarah Kelly", label: "Sarah Kelly" },
  { value: "Ken Loach", label: "Ken Loach" },
  { value: "Zhang Yuan", label: "Zhang Yuan" },
  { value: "Jon Blair", label: "Jon Blair" },
  { value: "Jerry Paris", label: "Jerry Paris" },
  { value: "Theodore Thomas", label: "Theodore Thomas" },
  { value: "Robert Redford", label: "Robert Redford" },
  { value: "Curtis Hanson", label: "Curtis Hanson" },
  { value: "Kevin Dowling", label: "Kevin Dowling" },
  { value: "Sam Weisman", label: "Sam Weisman" },
  { value: "Lewis Teague", label: "Lewis Teague" },
  { value: "Archie Mayo", label: "Archie Mayo" },
  { value: "Art Stevens", label: "Art Stevens" },
  { value: "Daniel Vigne", label: "Daniel Vigne" },
  { value: "Otto Preminger", label: "Otto Preminger" },
  { value: "Paul Lynch", label: "Paul Lynch" },
  { value: "John Warren", label: "John Warren" },
  { value: "Tim Robbins", label: "Tim Robbins" },
  { value: "Alan Smithee", label: "Alan Smithee" },
  { value: "Joshua Logan", label: "Joshua Logan" },
  { value: "Harold Becker", label: "Harold Becker" },
  { value: "Des McAnuff", label: "Des McAnuff" },
  { value: "Jafar Panahi", label: "Jafar Panahi" },
  { value: "Oliver Parker", label: "Oliver Parker" },
  { value: "Ron Howard", label: "Ron Howard" },
  { value: "Suri Krishnamma", label: "Suri Krishnamma" },
  { value: "John Ford", label: "John Ford" },
  { value: "Ken Annakin", label: "Ken Annakin" },
  { value: "Michael Curtiz", label: "Michael Curtiz" },
  { value: "Vincent Robert", label: "Vincent Robert" },
  { value: "Robert Bierman", label: "Robert Bierman" },
];

export const actors = [
    { value: "Jennifer Love Hewitt", label: "Jennifer Love Hewitt" },
    { value: "Courteney Cox", label: "Courteney Cox" },
    { value: "Patrick Swayze", label: "Patrick Swayze" },
    { value: "Claire Danes", label: "Claire Danes" },
    { value: "Michael Mills", label: "Michael Mills" },
    { value: "Ted Cruddace", label: "Ted Cruddace" },
    { value: "Gordon Greene", label: "Gordon Greene" },
    { value: "Joseph Anderson", label: "Joseph Anderson" },
    { value: "Nunzia Greco", label: "Nunzia Greco" },
    { value: "Barney Martin", label: "Barney Martin" },
    { value: "Rywka Wajsbrot", label: "Rywka Wajsbrot" },
    { value: "Tracy Dali", label: "Tracy Dali" },
    { value: "Charles Trowbridge", label: "Charles Trowbridge" },
    { value: "Nance O'Neil", label: "Nance O'Neil" },
    { value: "Betty Compson", label: "Betty Compson" },
    { value: "Bill Miller", label: "Bill Miller" },
    { value: "Luis Trenker", label: "Luis Trenker" },
    { value: "Richard Connaught", label: "Richard Connaught" },
    { value: "Valorie Armstrong", label: "Valorie Armstrong" },
    { value: "Patrice Martinez", label: "Patrice Martinez" },
    { value: "John Cappon", label: "John Cappon" },
    { value: "Josif Tatić", label: "Josif Tatić" },
    { value: "Barry Humphries", label: "Barry Humphries" },
    { value: "Hunt Holman", label: "Hunt Holman" },
    { value: "Jan Smook", label: "Jan Smook" }
];

export const genres = [
  { value: "Family", label: "Family" },
  { value: "Crime", label: "Crime" },
  { value: "Animation", label: "Animation" },
  { value: "Documentary", label: "Documentary" },
  { value: "Romance", label: "Romance" },
  { value: "Mystery", label: "Mystery" },
  { value: "History", label: "History" },
  { value: "Music", label: "Music" },
  { value: "Fantasy", label: "Fantasy" },
  { value: "TV Movie", label: "TV Movie" },
  { value: "Science Fiction", label: "Science Fiction" },
  { value: "Foreign", label: "Foreign" },
  { value: "Horror", label: "Horror" },
  { value: "Drama", label: "Drama" },
  { value: "Action", label: "Action" },
  { value: "Thriller", label: "Thriller" },
  { value: "Western", label: "Western" },
  { value: "Comedy", label: "Comedy" },
  { value: "Adventure", label: "Adventure" },
  { value: "War", label: "War" }
];
